# This workflows will create a new demo repository using The Hatchlor for demonstration purposes

name: Build demo

on:
  workflow_dispatch:

jobs:
  make-demo:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        path: ./hatchlor-template

    - name: Setup Python environment
      uses: mamba-org/setup-micromamba@v1
      with:
          micromamba-version: 'latest'
          environment-file: ./hatchlor-template/.github/test_environment.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'

    - name: Setup git
      run: |
        git config --global user.email "github.action@example.com"
        git config --global user.name "Github Action"

    - name: Run cookiecutter
      run: cookiecutter --no-input ./hatchlor-template

    - name: Test some hatch commands
      working-directory: ./python-hatch-project
      run: |
        hatch run fibonacci 10
        hatch run cov
        hatch run lint:all
        hatch run pre-commit run --all-files

    - name: Push to the-hatchlor-demo
      uses: cpina/github-action-push-to-another-repository@devel
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: "python-hatch-project"
        destination-github-username: "FlorianWilhelm"
        destination-repository-username: "FlorianWilhelm"
        destination-repository-name: "the-hatchlor-demo"
        user-email: florian.wilhelm@gmail.com
        target-branch: main
