# This workflows will create a new demo repository using The Hatchlor for demonstration purposes

name: Run tests

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        path: ./hatchlor-template

    - name: Setup Python environment
      uses: mamba-org/setup-micromamba@v1
      with:
          micromamba-version: 'latest'
          environment-file: ./hatchlor-template/.github/test_environment.yml
          init-shell: >-
            bash
            powershell
          cache-environment: true
          post-cleanup: 'all'

    - name: Setup git
      run: |
        git config --global user.email "github.action@example.com"
        git config --global user.name "Github Action"

    - name: Run cookiecutter
      run: cookiecutter --no-input ./hatchlor-template
      shell: bash -el {0}

    - name: Test some hatch commands
      run: |
        hatch run fibonacci 10
        hatch run cov
        hatch run lint:all
        hatch run pre-commit run --all-files
      shell: bash -el {0}
      
